### ISSUE TITLE
[client] ui fix

### ISSUE THREAD

**Issue by Jinho1011** [TeamDivers/Soar#34]
## Description

- Some changes are needed to match the differences in the Figma design layout

## Todo

- [x] bottomSheet Backdrop need to be darken
<img width="382" alt="image" src="https://github.com/TeamDivers/Soar/assets/26860466/c8a2cf9e-86e4-41ec-93c7-30d2f6c0698a">

- [x] delete button should only be dragged to the right edge boundary of the screen
<img width="468" alt="image" src="https://github.com/TeamDivers/Soar/assets/26860466/d1f9296e-fc2d-4b30-aa6c-2796a3032842">

- [x] float button for create new portfolio is needed
<img width="202" alt="image" src="https://github.com/TeamDivers/Soar/assets/26860466/ca5e888f-f956-4438-aca3-43b8e6af45fa">
