### ISSUE TITLE
[server] feat: 랭킹 로직 구현

### ISSUE THREAD

**Issue by anjm1020** [TeamDivers/Soar#41]
## Description

- 랭킹 시스템 로직 구현
- 무슨 랭킹을 어떤 기준으로 구할건가?
  - 포트폴리오 랭킹 -> 별점 평균
<img width="320" alt="image" src="https://github.com/TeamDivers/Soar/assets/26860466/0bdbe482-bbae-4f0e-a888-ccc4e7c93481">

- 특정 유저의 포트폴리오 목록을 반환할 때 각 포트폴리오의 순위가 포함되어야 합니다.

## Todo

- [x] 랭킹 관련 API 구현
- [x] 서비스 로직 구현
- [x] DTO에 순위 추가
